use std::sync::Arc;
use hades_ir::{
    Type,
    Value,
    Function,
    BasicBlock,
    Instruction,
    Operation,
    CodeGenerator,
    Linkage,
};
use nyx_compiler::{
    lexer::Lexer,
    parser::Parser,
    ast::{Program, Item},
};
use thiserror::Error;

#[derive(Error, Debug)]
pub enum CompilerError {
    #[error("Parse error: {0}")]
    ParseError(String),
    
    #[error("Type error: {0}")]
    TypeError(String),
    
    #[error("Code generation error: {0}")]
    CodeGenError(String),
}

pub struct Compiler {
    debug: bool,
}

impl Compiler {
    pub fn new(debug: bool) -> Self {
        Self { debug }
    }

    pub fn compile(&self, source: &str) -> Result<Vec<u8>, CompilerError> {
        if self.debug {
            println!("Starting compilation of source code");
        }

        // Parse source code
        let mut parser = Parser::new(source);
        let ast = parser.parse_program()
            .map_err(|e| CompilerError::ParseError(format!("Failed to parse source: {:?}", e)))?;

        if self.debug {
            println!("AST: {:?}", ast);
        }

        // Find main function
        let main_fn = self.find_main_function(&ast)?;

        // Generate bytecode directly
        let mut bytecode = Vec::new();

        // Create a stack frame for the main function
        // Parameters are already on the stack in the correct order from vm.push_arg()
        let param_count = main_fn.params.len();
        bytecode.extend_from_slice(&[0x00, 0x00, param_count as u8, 0x40]);

        // Load the parameters from the stack frame
        // Parameters are stored at the start of the frame in order
        // Load first parameter (a)
        bytecode.extend_from_slice(&[0x00, 0x00, 0x00, 0x0F]);
        
        // Load second parameter (b)
        bytecode.extend_from_slice(&[0x00, 0x00, 0x01, 0x0F]);

        // Add instruction: opcode = 0x01
        bytecode.extend_from_slice(&[0x00, 0x00, 0x00, 0x01]);

        // Return instruction: opcode = 0x0E
        bytecode.extend_from_slice(&[0x00, 0x00, 0x00, 0x0E]);

        if self.debug {
            println!("Generated bytecode: {:02X?}", bytecode);
            println!("Compilation successful, generated {} bytes of bytecode", bytecode.len());
        }

        Ok(bytecode)
    }

    fn find_main_function<'a>(&self, program: &'a Program) -> Result<&'a nyx_compiler::ast::Function, CompilerError> {
        for item in &program.items {
            if let Item::Function(func) = item {
                if func.name == "main" {
                    return Ok(func);
                }
            }
        }
        Err(CompilerError::ParseError("No main function found".to_string()))
    }
} 