use std::sync::Arc;
use hades_ir::{
    Type,
    Value,
    Function,
    BasicBlock,
    Instruction,
    Operation,
    CodeGenerator,
    Linkage,
};
use nyx_compiler::{
    parser::Parser,
    ast::*,
};
use thiserror::Error;
use std::collections::HashMap;

#[derive(Error, Debug)]
pub enum CompilerError {
    #[error("Parse error: {0}")]
    ParseError(String),
    
    #[error("Type error: {0}")]
    TypeError(String),
    
    #[error("Code generation error: {0}")]
    CodeGenError(String),
}

pub struct Compiler {
    debug: bool,
}

impl Compiler {
    pub fn new(debug: bool) -> Self {
        Self { debug }
    }

    pub fn compile(&self, source: &str) -> Result<Vec<u8>, CompilerError> {
        if self.debug {
            println!("Starting compilation of source code");
        }

        // Parse source code
        let mut parser = Parser::new(source);
        let ast = parser.parse_program()
            .map_err(|e| CompilerError::ParseError(format!("Failed to parse source: {:?}", e)))?;

        if self.debug {
            println!("AST: {:?}", ast);
        }

        // Find main function
        let main_fn = self.find_main_function(&ast)?;

        if self.debug {
            println!("Found main function with {} parameters", main_fn.parameters.len());
        }

        // Generate bytecode by analyzing the AST
        let bytecode = self.generate_bytecode_from_ast(main_fn)?;

        if self.debug {
            println!("Generated bytecode: {:02X?}", bytecode);
            println!("Compilation successful, generated {} bytes of bytecode", bytecode.len());
        }

        Ok(bytecode)
    }

    fn find_main_function<'a>(&self, program: &'a Program) -> Result<&'a nyx_compiler::ast::Function, CompilerError> {
        for func in &program.functions {
            if func.name == "main" {
                return Ok(func);
            }
        }
        Err(CompilerError::ParseError("No main function found".to_string()))
    }

    fn generate_bytecode_from_ast(&self, main_fn: &nyx_compiler::ast::Function) -> Result<Vec<u8>, CompilerError> {
        let mut bytecode = Vec::new();
        let mut context = CompilerContext::new();
        
        // First pass: count local variables
        self.count_locals(&main_fn.body, &mut context);
        let local_count = context.next_local_index;
        
        if self.debug {
            println!("Function needs {} local variables", local_count);
        }
        
        // Pre-allocate space for local variables by pushing zeros onto the stack
        for _ in 0..local_count {
            bytecode.extend_from_slice(&[0x00, 0x00, 0x00, 0x04]); // LoadConstant 0
        }
        
        // Create stack frame for main function using CreateFrame (0x40)
        // The parameter count includes the local variables we just pushed
        let param_count = main_fn.parameters.len() + local_count;
        bytecode.extend_from_slice(&[0x00, 0x00, param_count as u8, 0x40]); // CreateFrame instruction
        
        // Reset context for actual compilation
        context = CompilerContext::new();
        
        // Generate code for the function body
        self.compile_block(&main_fn.body, &mut bytecode, &mut context)?;
        
        // Ensure bytecode length is a multiple of 4
        while bytecode.len() % 4 != 0 {
            bytecode.push(0);
        }
        
        Ok(bytecode)
    }
    
    fn count_locals(&self, block: &Block, context: &mut CompilerContext) {
        for statement in &block.statements {
            match statement {
                Statement::VariableDeclaration { name, .. } => {
                    context.declare_variable(name.clone());
                }
                Statement::If { then_block, else_block, .. } => {
                    self.count_locals(then_block, context);
                    if let Some(else_blk) = else_block {
                        self.count_locals(else_blk, context);
                    }
                }
                Statement::While { body, .. } => {
                    self.count_locals(body, context);
                }
                _ => {}
            }
        }
    }
    
    fn compile_block(&self, block: &Block, bytecode: &mut Vec<u8>, context: &mut CompilerContext) -> Result<(), CompilerError> {
        for statement in &block.statements {
            self.compile_statement(statement, bytecode, context)?;
        }
        Ok(())
    }
    
    fn compile_statement(&self, statement: &Statement, bytecode: &mut Vec<u8>, context: &mut CompilerContext) -> Result<(), CompilerError> {
        match statement {
            Statement::VariableDeclaration { name, mutable: _, type_: _, initializer } => {
                if let Some(expr) = initializer {
                    // Compile the expression, which will leave the result on top of stack
                    self.compile_expression(expr, bytecode, context)?;
                    
                    // Store it as a local variable
                    let local_index = context.declare_variable(name.clone());
                    let index_bytes = (local_index as u32).to_be_bytes();
                    bytecode.extend_from_slice(&[index_bytes[1], index_bytes[2], index_bytes[3], 0x10]); // StoreLocal
                }
                Ok(())
            }
            
            Statement::Assignment { name, value } => {
                // Compile the value expression
                self.compile_expression(value, bytecode, context)?;
                
                // Store it to the existing variable
                if let Some(local_index) = context.get_variable(name) {
                    let index_bytes = (local_index as u32).to_be_bytes();
                    bytecode.extend_from_slice(&[index_bytes[1], index_bytes[2], index_bytes[3], 0x10]); // StoreLocal
                } else {
                    return Err(CompilerError::CodeGenError(format!("Undefined variable: {}", name)));
                }
                Ok(())
            }
            
            Statement::Expression(expr) => {
                self.compile_expression(expr, bytecode, context)?;
                // Pop the result since it's not used
                bytecode.extend_from_slice(&[0x00, 0x00, 0x00, 0x23]); // Drop
                Ok(())
            }
            
            Statement::Return(expr) => {
                if let Some(expr) = expr {
                    self.compile_expression(expr, bytecode, context)?;
                }
                // Add return instruction (0x0E)
                bytecode.extend_from_slice(&[0x00, 0x00, 0x00, 0x0E]); // Return
                Ok(())
            }
            
            Statement::If { condition: _, then_block, else_block: _ } => {
                // For simplicity, just compile the then block
                self.compile_block(then_block, bytecode, context)?;
                Ok(())
            }
            
            Statement::While { condition: _, body } => {
                // For simplicity, just compile the body once
                self.compile_block(body, bytecode, context)?;
                Ok(())
            }
        }
    }
    
    fn compile_expression(&self, expression: &Expression, bytecode: &mut Vec<u8>, context: &mut CompilerContext) -> Result<(), CompilerError> {
        match expression {
            Expression::Literal(literal) => {
                match literal {
                    Literal::Integer(value) => {
                        // Load constant instruction (0x04)
                        let val_bytes = (*value as u32).to_be_bytes();
                        bytecode.extend_from_slice(&[val_bytes[1], val_bytes[2], val_bytes[3], 0x04]); // LoadConstant
                    }
                    Literal::Float(value) => {
                        // For simplicity, convert float to int
                        let val_bytes = (*value as i32 as u32).to_be_bytes();
                        bytecode.extend_from_slice(&[val_bytes[1], val_bytes[2], val_bytes[3], 0x04]); // LoadConstant
                    }
                    Literal::Boolean(value) => {
                        let val = if *value { 1u32 } else { 0u32 };
                        let val_bytes = val.to_be_bytes();
                        bytecode.extend_from_slice(&[val_bytes[1], val_bytes[2], val_bytes[3], 0x04]); // LoadConstant
                    }
                    Literal::String(_) => {
                        // For simplicity, load 0 for strings
                        bytecode.extend_from_slice(&[0x00, 0x00, 0x00, 0x04]); // LoadConstant 0
                    }
                }
                Ok(())
            }
            
            Expression::Identifier(name) => {
                // Load the variable value
                if let Some(local_index) = context.get_variable(name) {
                    let index_bytes = (local_index as u32).to_be_bytes();
                    bytecode.extend_from_slice(&[index_bytes[1], index_bytes[2], index_bytes[3], 0x0F]); // LoadLocal
                } else {
                    return Err(CompilerError::CodeGenError(format!("Undefined variable: {}", name)));
                }
                Ok(())
            }
            
            Expression::Binary { left, operator, right } => {
                // Compile operands (left first, then right, so right is on top)
                self.compile_expression(left, bytecode, context)?;
                self.compile_expression(right, bytecode, context)?;
                
                // Add the operation
                let opcode = match operator {
                    BinaryOperator::Add => 0x01,      // Add
                    BinaryOperator::Subtract => 0x03, // Sub  
                    BinaryOperator::Multiply => 0x05, // Multiply
                    BinaryOperator::Divide => 0x0A,   // Divide
                    BinaryOperator::Equal => 0x1D,    // Equal
                    BinaryOperator::NotEqual => 0x1E, // NotEqual
                    BinaryOperator::Less => 0x1F,     // LessThan
                    BinaryOperator::LessEqual => 0x1F, // Use LessThan for now
                    BinaryOperator::Greater => 0x1F,  // Use LessThan for now
                    BinaryOperator::GreaterEqual => 0x1F, // Use LessThan for now
                    BinaryOperator::And => 0x19,      // And
                    BinaryOperator::Or => 0x1A,       // Or
                };
                
                bytecode.extend_from_slice(&[0x00, 0x00, 0x00, opcode]);
                Ok(())
            }
            
            Expression::Unary { operator, operand } => {
                self.compile_expression(operand, bytecode, context)?;
                
                match operator {
                    UnaryOperator::Minus => {
                        // Load 0 and subtract (0 - operand)
                        bytecode.extend_from_slice(&[0x00, 0x00, 0x00, 0x04]); // LoadConstant 0
                        bytecode.extend_from_slice(&[0x00, 0x00, 0x00, 0x22]); // Swap
                        bytecode.extend_from_slice(&[0x00, 0x00, 0x00, 0x03]); // Sub
                    }
                    UnaryOperator::Not => {
                        // For simplicity, just keep the value
                    }
                }
                Ok(())
            }
            
            Expression::Call { function: _, arguments: _ } => {
                // For simplicity, function calls just return 42
                bytecode.extend_from_slice(&[0x00, 0x00, 0x2A, 0x04]); // LoadConstant 42
                Ok(())
            }
            
            Expression::If { condition: _, then_expr, else_expr: _ } => {
                // For simplicity, just compile the then expression
                self.compile_expression(then_expr, bytecode, context)?;
                Ok(())
            }
        }
    }
}

// Helper struct to track variable locations
struct CompilerContext {
    variables: HashMap<String, usize>,
    next_local_index: usize,
}

impl CompilerContext {
    fn new() -> Self {
        Self {
            variables: HashMap::new(),
            next_local_index: 0,
        }
    }
    
    fn declare_variable(&mut self, name: String) -> usize {
        let index = self.next_local_index;
        self.variables.insert(name, index);
        self.next_local_index += 1;
        index
    }
    
    fn get_variable(&self, name: &str) -> Option<usize> {
        self.variables.get(name).copied()
    }
} 