use std::sync::Arc;
use vm::opcode::Opcode;
use crate::{
    error::{Error, Result},
    types::Type,
    value::Value,
};

/// The BytecodeGenerator converts IR constructs to Hades VM bytecode.
pub struct BytecodeGenerator {
    /// The generated bytecode as a vector of bytes
    bytecode: Vec<u8>,
    /// The current offset in the bytecode
    offset: usize,
}

impl BytecodeGenerator {
    /// Create a new bytecode generator
    pub fn new() -> Self {
        Self {
            bytecode: Vec::new(),
            offset: 0,
        }
    }
    
    /// Reset the generator
    pub fn reset(&mut self) {
        self.bytecode.clear();
        self.offset = 0;
    }
    
    /// Get the generated bytecode
    pub fn get_bytecode(&self) -> &[u8] {
        &self.bytecode
    }
    
    /// Generate a LoadConstant instruction (for demonstration)
    pub fn gen_load_constant(&mut self, value: i32) -> Result<()> {
        // LoadConstant takes a 24-bit operand and has opcode 0x04
        
        // Write the operand (big endian, 24 bits = 3 bytes)
        let bytes = value.to_be_bytes();
        self.bytecode.push(bytes[1]); // Skip the first byte (we only have 24 bits for operand)
        self.bytecode.push(bytes[2]);
        self.bytecode.push(bytes[3]);
        
        // Write the opcode
        self.bytecode.push(Opcode::LoadConstant as u8);
        
        self.offset += 4;
        Ok(())
    }
    
    /// Generate an Add instruction (for demonstration)
    pub fn gen_add(&mut self) -> Result<()> {
        // Add has no operands and opcode 0x01
        
        // Write padding for 24-bit operand field (which we don't use)
        self.bytecode.push(0);
        self.bytecode.push(0);
        self.bytecode.push(0);
        
        // Write the opcode
        self.bytecode.push(Opcode::Add as u8);
        
        self.offset += 4;
        Ok(())
    }
    
    /// Generate a Print instruction (for demonstration)
    pub fn gen_print(&mut self) -> Result<()> {
        // Print has no operands
        
        // Write padding for 24-bit operand field (which we don't use)
        self.bytecode.push(0);
        self.bytecode.push(0);
        self.bytecode.push(0);
        
        // Write the opcode
        self.bytecode.push(Opcode::Print as u8);
        
        self.offset += 4;
        Ok(())
    }
    
    /// Generate bytecode for an IR constant value
    pub fn gen_constant(&mut self, value: &Value) -> Result<()> {
        match value {
            Value::IntegerConstant { value, ty } => {
                match **ty {
                    Type::Integer(32) => {
                        // For i32, we can use LoadConstant directly
                        self.gen_load_constant(*value as i32)
                    },
                    Type::Integer(64) => {
                        // For i64, we might need to split it into two 32-bit values
                        // For simplicity, this example just truncates to i32
                        self.gen_load_constant(*value as i32)
                    },
                    _ => Err(Error::BytecodeGenerationError(
                        format!("Unsupported integer type for constant: {}", ty)
                    )),
                }
            },
            Value::FloatConstant { .. } => {
                // Float constants would require a different approach
                // For example, storing them in a constant pool and loading them
                Err(Error::BytecodeGenerationError(
                    "Float constants not implemented yet".to_string()
                ))
            },
            Value::BooleanConstant { value } => {
                // For boolean, we can use 0 or 1
                self.gen_load_constant(if *value { 1 } else { 0 })
            },
            _ => Err(Error::BytecodeGenerationError(
                format!("Unsupported constant type: {:?}", value)
            )),
        }
    }
    
    /// Generate a simple addition program (for demonstration)
    pub fn gen_sample_addition_program(&mut self, a: i32, b: i32) -> Result<()> {
        // Generate: LoadConstant a, LoadConstant b, Add, Print
        self.gen_load_constant(a)?;
        self.gen_load_constant(b)?;
        self.gen_add()?;
        self.gen_print()?;
        
        Ok(())
    }
    
    /// Emit raw bytes to the bytecode (for executable generation)
    pub fn emit_raw_bytes(&mut self, bytes: &[u8]) -> Result<()> {
        self.bytecode.extend_from_slice(bytes);
        self.offset += bytes.len();
        Ok(())
    }
}

impl Default for BytecodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::Type;
    use crate::value::Value;
    
    #[test]
    fn test_generate_load_constant() {
        let mut gen = BytecodeGenerator::new();
        gen.gen_load_constant(42).unwrap();
        
        let bytecode = gen.get_bytecode();
        assert_eq!(bytecode.len(), 4);
        
        // Check operand (24 bits = 3 bytes)
        assert_eq!(bytecode[0], 0);  // Most significant byte of 42 is 0
        assert_eq!(bytecode[1], 0);  // Second byte of 42 is 0
        assert_eq!(bytecode[2], 42); // Least significant byte of 42 is 42
        
        // Check opcode
        assert_eq!(bytecode[3], Opcode::LoadConstant as u8);
    }
    
    #[test]
    fn test_generate_addition_program() {
        let mut gen = BytecodeGenerator::new();
        gen.gen_sample_addition_program(3, 4).unwrap();
        
        let bytecode = gen.get_bytecode();
        assert_eq!(bytecode.len(), 16); // 4 instructions * 4 bytes each
        
        // Check LoadConstant 3
        assert_eq!(bytecode[0], 0);
        assert_eq!(bytecode[1], 0);
        assert_eq!(bytecode[2], 3);
        assert_eq!(bytecode[3], Opcode::LoadConstant as u8);
        
        // Check LoadConstant 4
        assert_eq!(bytecode[4], 0);
        assert_eq!(bytecode[5], 0);
        assert_eq!(bytecode[6], 4);
        assert_eq!(bytecode[7], Opcode::LoadConstant as u8);
        
        // Check Add
        assert_eq!(bytecode[8], 0);
        assert_eq!(bytecode[9], 0);
        assert_eq!(bytecode[10], 0);
        assert_eq!(bytecode[11], Opcode::Add as u8);
        
        // Check Print
        assert_eq!(bytecode[12], 0);
        assert_eq!(bytecode[13], 0);
        assert_eq!(bytecode[14], 0);
        assert_eq!(bytecode[15], Opcode::Print as u8);
    }
    
    #[test]
    fn test_generate_from_ir_constant() {
        let mut gen = BytecodeGenerator::new();
        
        // Create an IR integer constant
        let int_type = Type::i32();
        let int_value = Value::integer_constant(42, int_type);
        
        // Generate bytecode for it
        gen.gen_constant(&int_value).unwrap();
        
        let bytecode = gen.get_bytecode();
        assert_eq!(bytecode.len(), 4);
        
        // Check operand (24 bits = 3 bytes)
        assert_eq!(bytecode[0], 0);  // Most significant byte of 42 is 0
        assert_eq!(bytecode[1], 0);  // Second byte of 42 is 0
        assert_eq!(bytecode[2], 42); // Least significant byte of 42 is 42
        
        // Check opcode
        assert_eq!(bytecode[3], Opcode::LoadConstant as u8);
    }
} 