use std::sync::Arc;
use std::collections::HashMap;

use crate::{
    Function,
    Value,
    Type,
    BasicBlock,
    Instruction,
    Operation,
    error::{Error, Result},
};

/// Represents a code generation context
pub struct CodeGenContext {
    /// Maps Values to their positions in the constant pool
    constant_pool_indices: HashMap<Value, usize>,
    /// The constant pool containing all constants used in the program
    constant_pool: Vec<Value>,
    /// Maps BasicBlock IDs to their positions in the bytecode
    block_positions: HashMap<String, usize>,
    /// The generated bytecode
    bytecode: Vec<u8>,
}

impl CodeGenContext {
    /// Create a new code generation context
    pub fn new() -> Self {
        Self {
            constant_pool_indices: HashMap::new(),
            constant_pool: Vec::new(),
            block_positions: HashMap::new(),
            bytecode: Vec::new(),
        }
    }

    /// Add a constant to the constant pool and return its index
    fn add_constant(&mut self, value: Value) -> usize {
        if let Some(&index) = self.constant_pool_indices.get(&value) {
            return index;
        }
        let index = self.constant_pool.len();
        self.constant_pool.push(value.clone());
        self.constant_pool_indices.insert(value, index);
        index
    }

    /// Emit a byte into the bytecode
    fn emit(&mut self, byte: u8) {
        self.bytecode.push(byte);
    }

    /// Emit multiple bytes into the bytecode
    fn emit_bytes(&mut self, bytes: &[u8]) {
        self.bytecode.extend_from_slice(bytes);
    }

    /// Emit a 32-bit integer in little-endian format
    fn emit_u32(&mut self, value: u32) {
        self.emit_bytes(&value.to_le_bytes());
    }

    /// Get the current position in the bytecode
    fn current_position(&self) -> usize {
        self.bytecode.len()
    }

    /// Generate code for a constant value
    fn gen_constant(&mut self, value: &Value) -> Result<()> {
        let index = self.add_constant(value.clone());
        // Emit LOAD_CONST instruction with the constant pool index
        self.emit(0x01); // LOAD_CONST opcode (was 0x04)
        self.emit_u32(index as u32);
        Ok(())
    }

    /// Generate code for a binary operation
    fn gen_binary_op(&mut self, op: &Operation, operands: &[Value]) -> Result<()> {
        // Generate code for operands
        for operand in operands {
            self.gen_value(operand)?;
        }

        // Emit the appropriate opcode for the operation
        let opcode = match op {
            Operation::Add => 0x10, // ADD opcode (was 0x01)
            Operation::Sub => 0x03, // Sub opcode
            Operation::Mul => 0x05, // Multiply opcode
            Operation::Div => 0x0A, // Divide opcode
            _ => return Err(Error::CodeGenError(format!(
                "Unsupported binary operation: {:?}",
                op
            ))),
        };
        self.emit(opcode);
        Ok(())
    }

    /// Generate code for a value
    fn gen_value(&mut self, value: &Value) -> Result<()> {
        match value {
            Value::IntegerConstant { .. } |
            Value::FloatConstant { .. } |
            Value::BooleanConstant { .. } |
            Value::CharConstant { .. } |
            Value::StringConstant { .. } => self.gen_constant(value),
            
            Value::Argument { id, .. } => {
                // Load argument from the appropriate slot
                self.emit(0x02); // LOAD_ARG opcode (was 0x0F)
                // Emit 8-byte argument ID
                let id_bytes = (id.raw() as u64).to_le_bytes();
                self.emit_bytes(&id_bytes);
                Ok(())
            },
            
            Value::Instruction { .. } => {
                // Instructions should be handled separately in gen_instruction
                Ok(())
            },
            
            _ => Err(Error::CodeGenError(format!(
                "Unsupported value type: {:?}",
                value
            ))),
        }
    }

    /// Generate code for an instruction
    fn gen_instruction(&mut self, instruction: &Instruction) -> Result<()> {
        match instruction.operation() {
            Operation::Add | Operation::Sub | Operation::Mul | Operation::Div => {
                self.gen_binary_op(instruction.operation(), instruction.operands())
            },
            
            Operation::Load => {
                let ptr = &instruction.operands()[0];
                self.gen_value(ptr)?;
                self.emit(0x20); // LOAD opcode (was 0x07)
                Ok(())
            },
            
            Operation::Store => {
                let value = &instruction.operands()[0];
                let ptr = &instruction.operands()[1];
                self.gen_value(value)?;
                self.gen_value(ptr)?;
                self.emit(0x21); // STORE opcode (was 0x08)
                Ok(())
            },
            
            Operation::Ret => {
                if let Some(value) = instruction.operands().first() {
                    self.gen_value(value)?;
                }
                self.emit(0xFF); // RET opcode (was 0x0E)
                Ok(())
            },
            
            _ => Err(Error::CodeGenError(format!(
                "Unsupported instruction: {:?}",
                instruction.operation()
            ))),
        }
    }

    /// Generate code for a basic block
    fn gen_basic_block(&mut self, block: &BasicBlock) -> Result<()> {
        // Record the position of this block
        self.block_positions.insert(block.id().to_string(), self.current_position());

        // Generate code for each instruction in the block
        for instruction in block.instructions() {
            self.gen_instruction(instruction)?;
        }

        Ok(())
    }

    /// Generate code for a function
    pub fn gen_function(&mut self, function: &Function) -> Result<()> {
        // Generate prologue
        self.emit(0x00); // ENTER opcode (was 0x0D)
        self.emit_u32(function.parameters().len() as u32);

        // Generate code for each basic block
        for block in function.basic_blocks() {
            self.gen_basic_block(block)?;
        }

        Ok(())
    }

    /// Get the generated bytecode
    pub fn get_bytecode(&self) -> &[u8] {
        &self.bytecode
    }

    /// Get the constant pool
    pub fn get_constant_pool(&self) -> &[Value] {
        &self.constant_pool
    }
}

/// The main code generator
pub struct CodeGenerator;

impl CodeGenerator {
    /// Create a new code generator
    pub fn new() -> Self {
        Self
    }

    /// Generate code for a function
    pub fn generate(&self, function: &Function) -> Result<(Vec<u8>, Vec<Value>)> {
        let mut context = CodeGenContext::new();
        context.gen_function(function)?;
        Ok((context.bytecode, context.constant_pool))
    }
} 