use std::sync::Arc;
use std::cell::RefCell;

use hades_ir::{
    BasicBlock,
    Builder,
    BytecodeGenerator,
    Context,
    Result,
    Function,
    Linkage,
    Operation,
    Module,
    Type,
    Value,
};

/// This example demonstrates how to use the Hades IR to build a simple function
/// that computes the sum of two numbers, with control flow.
fn main() -> Result<()> {
    // Create a compilation context
    let context = Arc::new(Context::new());
    
    // Create a module
    let mut module = Module::new_root(context.clone(), "example_module".to_string());
    module.set_source_file("ir_demonstration.rs".to_string());
    
    // Create a function type: (i32, i32) -> i32
    let i32_type = Type::i32();
    let param_types = vec![i32_type.clone(), i32_type.clone()];
    let function_type = Type::function(i32_type.clone(), param_types, false);
    
    // Create a function: int add_or_multiply(int a, int b)
    let mut function = Function::new(
        "add_or_multiply".to_string(),
        function_type,
        Linkage::External
    )?;
    
    // Add parameters to the function
    let param_a = function.add_parameter(Some("a".to_string()), i32_type.clone())?;
    let param_b = function.add_parameter(Some("b".to_string()), i32_type.clone())?;
    
    // Create basic blocks for the function
    let entry_block = Arc::new(RefCell::new(BasicBlock::named("entry")));
    let add_block = Arc::new(RefCell::new(BasicBlock::named("add")));
    let mul_block = Arc::new(RefCell::new(BasicBlock::named("mul")));
    let exit_block = Arc::new(RefCell::new(BasicBlock::named("exit")));
    
    // Add blocks to the function and store their IDs
    let entry_id = function.add_basic_block((*entry_block.borrow()).clone());
    let add_id = function.add_basic_block((*add_block.borrow()).clone());
    let mul_id = function.add_basic_block((*mul_block.borrow()).clone());
    let exit_id = function.add_basic_block((*exit_block.borrow()).clone());
    
    // Create a builder and set its insertion point to the entry block
    let mut builder = Builder::new(context.clone());
    
    // Build the entry block
    builder.position_at_end(entry_block.clone());
    let a_value = param_a.to_value();
    let b_value = param_b.to_value();
    let ten = Value::integer_constant(10, i32_type.clone());
    let cond = builder.build_cmp(Operation::Gt, a_value.clone(), ten, Some("cmp"))?;
    builder.build_cond_br(cond, add_block.borrow().to_value(), mul_block.borrow().to_value())?;
    function.find_basic_block_mut(entry_id).unwrap().add_instructions(entry_block.borrow().instructions().to_vec());
    
    // Build the add block
    builder.position_at_end(add_block.clone());
    let add_result = builder.build_add(a_value.clone(), b_value.clone(), Some("add"))?;
    builder.build_br(exit_block.borrow().to_value())?;
    function.find_basic_block_mut(add_id).unwrap().add_instructions(add_block.borrow().instructions().to_vec());
    
    // Build the multiply block
    builder.position_at_end(mul_block.clone());
    let mul_result = builder.build_mul(a_value, b_value, Some("mul"))?;
    builder.build_br(exit_block.borrow().to_value())?;
    function.find_basic_block_mut(mul_id).unwrap().add_instructions(mul_block.borrow().instructions().to_vec());
    
    // Build the exit block
    builder.position_at_end(exit_block.clone());
    let phi_values = vec![
        (add_result.clone(), add_block.borrow().to_value()),
        (mul_result, mul_block.borrow().to_value()),
    ];
    let result = builder.build_phi(i32_type.clone(), phi_values, Some("result"))?;
    builder.build_print(result.clone())?;
    builder.build_ret(Some(result))?;
    function.find_basic_block_mut(exit_id).unwrap().add_instructions(exit_block.borrow().instructions().to_vec());
    
    // Add the function to the module
    module.add_function(function)?;
    
    // Verify the module
    module.verify()?;
    
    // Print the IR module
    println!("Generated IR:\n{}", module);
    
    // Generate bytecode for a sample call
    let mut gen = BytecodeGenerator::new();
    gen.gen_load_constant(15)?;
    gen.gen_load_constant(7)?;
    gen.gen_add()?;
    gen.gen_print()?;
    
    // Get and print the bytecode
    let bytecode = gen.get_bytecode();
    println!("\nGenerated bytecode for a simple addition:");
    for (i, chunk) in bytecode.chunks(4).enumerate() {
        print!("{:04x}: ", i * 4);
        for byte in chunk {
            print!("{:02x} ", byte);
        }
        if chunk.len() == 4 {
            let opcode_byte = chunk[3];
            let opcode_name = match opcode_byte {
                0x01 => "Add",
                0x04 => "LoadConstant",
                0x06 => "Print",
                _ => "Unknown",
            };
            print!("  ; {}", opcode_name);
            if opcode_byte == 0x04 {
                let value = ((chunk[0] as i32) << 16) | ((chunk[1] as i32) << 8) | (chunk[2] as i32);
                print!(" {}", value);
            }
        }
        println!();
    }
    
    println!("\nResult when executed on the VM would be: 22");
    Ok(())
} 