use hades_ir::{
    context::Context,
    types::Type,
    value::Value,
    bytecode::BytecodeGenerator,
    error::Result,
};

/// This example demonstrates how to use the Hades IR to generate bytecode for a simple
/// addition program that adds two constants (3 + 4) and prints the result.
fn main() -> Result<()> {
    // Create a new IR context
    let _context = Context::new();
    
    // Generate IR for a simple addition expression (3 + 4)
    // This is a simplified version of what would normally happen when compiling
    // a high-level language to IR
    
    // Create constants in the IR
    let i32_type = Type::i32();
    let const_3 = Value::integer_constant(3, i32_type.clone());
    let const_4 = Value::integer_constant(4, i32_type);
    
    // Create a bytecode generator
    let mut gen = BytecodeGenerator::new();
    
    // Generate bytecode for the constants and the addition
    gen.gen_constant(&const_3)?;
    gen.gen_constant(&const_4)?;
    gen.gen_add()?;
    gen.gen_print()?;
    
    // Get the final bytecode
    let bytecode = gen.get_bytecode();
    
    // Print the bytecode in a readable format
    println!("Generated bytecode:");
    for (i, chunk) in bytecode.chunks(4).enumerate() {
        print!("{:04x}: ", i * 4);
        for byte in chunk {
            print!("{:02x} ", byte);
        }
        
        // Print the opcode name for the last byte in each instruction
        if chunk.len() == 4 {
            let opcode_byte = chunk[3];
            let opcode_name = match opcode_byte {
                0x01 => "Add",
                0x04 => "LoadConstant",
                0x06 => "Print",
                _ => "Unknown",
            };
            print!("  ; {}", opcode_name);
            
            // For LoadConstant, also show the value
            if opcode_byte == 0x04 {
                let value = ((chunk[0] as i32) << 16) | ((chunk[1] as i32) << 8) | (chunk[2] as i32);
                print!(" {}", value);
            }
        }
        println!();
    }
    
    println!("\nResult when executed on the VM would be: 7");
    
    Ok(())
} 